/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indooptik.internalframe;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EtchedBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import indooptik.controller.FrameTransactionController;
import indooptik.jdialog.CustomerDialog;
import indooptik.jdialog.FrameDialog;
import indooptik.jdialog.LensDialog;
import indooptik.main.Main;
import indooptik.model.Transaction;

/**
 *
 * @author Yoeda H
 */
public class FrameTransactionInternalFrame extends javax.swing.JInternalFrame implements DocumentListener{    

	private static final long serialVersionUID = 2548499199696905680L;
	private FrameTransactionController frameTransactionController;
	private String customerId;
	private Integer lensId;
	private Integer frameId;
	private SimpleDateFormat sdf;
	
	public Integer getFrameId() {
		return frameId;
	}

	public void setFrameId(Integer frameId) {
		this.frameId = frameId;
	}

	public Integer getLensId() {
		return lensId;
	}

	public void setLensId(Integer lensId) {
		this.lensId = lensId;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	/**
	 * Creates new form DisplayTable
	 */
	public FrameTransactionInternalFrame() {
		initComponents();
	}    

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {
		
		sdf = new SimpleDateFormat("dd/MM/yyyy");

		exitBtn = new javax.swing.JButton();
		panel1 = new indooptik.utility.Panel();
		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBounds(10, -14, 560, 560);
		jPanel2 = new javax.swing.JPanel();
		jPanel2.setBounds(10, 10, 540, 71);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setBounds(12, 13, 75, 15);
		transactionIdLabel = new javax.swing.JLabel();
		transactionIdLabel.setBounds(93, 13, 75, 15);
		jLabel26 = new javax.swing.JLabel();
		jLabel26.setBounds(309, 13, 75, 15);
		dateLabel = new javax.swing.JLabel();
		dateLabel.setBounds(390, 13, 75, 15);
		customerPanel = new javax.swing.JPanel();
		customerPanel.setBounds(10, 92, 540, 130);
		nameTxt = new javax.swing.JTextField();
		nameTxt.setBounds(97, 13, 250, 20);
		nameLabel = new javax.swing.JLabel();
		nameLabel.setBounds(10, 10, 75, 20);
		teleponLabel = new javax.swing.JLabel();
		teleponLabel.setBounds(10, 40, 75, 20);
		teleponTxt = new javax.swing.JTextField();
		teleponTxt.setBounds(97, 42, 250, 20);
		bodLabel = new javax.swing.JLabel();
		bodLabel.setBounds(10, 100, 75, 20);
		hpLabel = new javax.swing.JLabel();
		hpLabel.setBounds(10, 70, 75, 20);
		mobileTxt = new javax.swing.JTextField();
		mobileTxt.setBounds(97, 73, 250, 20);
		bodTxt = new com.toedter.calendar.JDateChooser();
		bodTxt.setBounds(97, 101, 100, 20);
		lensPanel = new javax.swing.JPanel();
		lensPanel.setBounds(10, 233, 540, 170);
		lensLabel = new javax.swing.JLabel();
		lensLabel.setBounds(10, 10, 75, 20);
		lensTxt = new javax.swing.JTextField();
		lensTxt.setBounds(97, 13, 250, 20);
		lensColorLabel = new javax.swing.JLabel();
		lensColorLabel.setBounds(12, 46, 75, 20);
		lensColorTxt = new javax.swing.JTextField();
		lensColorTxt.setBounds(97, 44, 250, 20);
		jLabel10 = new javax.swing.JLabel();
		jLabel10.setBounds(12, 77, 75, 20);
		jLabel11 = new javax.swing.JLabel();
		jLabel11.setBounds(205, 77, 35, 15);
		jLabel12 = new javax.swing.JLabel();
		jLabel12.setBounds(378, 77, 35, 15);
		jLabel13 = new javax.swing.JLabel();
		jLabel13.setBounds(12, 108, 75, 20);
		jLabel14 = new javax.swing.JLabel();
		jLabel14.setBounds(205, 108, 35, 15);
		jLabel15 = new javax.swing.JLabel();
		jLabel15.setBounds(378, 108, 35, 15);
		jLabel24 = new javax.swing.JLabel();
		jLabel24.setBounds(12, 139, 75, 20);
		jLabel16 = new javax.swing.JLabel();
		jLabel16.setBounds(205, 142, 35, 15);
		pdTxt = new javax.swing.JTextField();
		pdTxt.setBounds(245, 140, 100, 20);
		framePanel = new javax.swing.JPanel();
		framePanel.setBounds(10, 414, 540, 160);
		frameTxt = new javax.swing.JTextField();
		frameTxt.setBounds(97, 13, 250, 20);
		frameLabel = new javax.swing.JLabel();
		frameLabel.setBounds(10, 10, 75, 20);
		frameDescLabel = new javax.swing.JLabel();
		frameDescLabel.setBounds(10, 40, 75, 20);
		jScrollPane1 = new javax.swing.JScrollPane();
		jScrollPane1.setBounds(97, 44, 426, 96);
		frameDescText = new javax.swing.JTextArea();
		jPanel7 = new javax.swing.JPanel();
		jPanel7.setBounds(580, 0, 370, 600);
		jPanel6 = new javax.swing.JPanel();
		jPanel6.setBounds(10, 10, 350, 510);
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setBounds(10, 10, 80, 20);
		lensPriceTextField = new javax.swing.JTextField();
		lensPriceTextField.setBounds(130, 10, 200, 20);
		
		lensPriceTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		jLabel18 = new javax.swing.JLabel();
		jLabel18.setBounds(10, 40, 80, 20);
		framePriceTextField = new javax.swing.JTextField();
		framePriceTextField.setBounds(130, 40, 200, 20);
		
		framePriceTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		jLabel20 = new javax.swing.JLabel();
		jLabel20.setBounds(10, 70, 80, 20);
		diskonTextField = new javax.swing.JTextField();
		diskonTextField.setBounds(130, 70, 200, 20);
		
		diskonTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		jLabel21 = new javax.swing.JLabel();
		jLabel21.setBounds(10, 100, 80, 20);
		totalBayarTextField = new javax.swing.JTextField();
		totalBayarTextField.setBounds(130, 100, 200, 20);
		
		jLabel23 = new javax.swing.JLabel();
		jLabel23.setBounds(22, 480, 75, 15);
		sisaTextField = new javax.swing.JTextField();
		sisaTextField.setBounds(130, 480, 200, 20);
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setBounds(12, 130, 100, 50);
		cashChkbox = new javax.swing.JCheckBox();
		cashChkbox.setBounds(130, 130, 95, 20);

		cashChkbox.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (cashChkbox.isSelected()) {
					dpCashTextField.setEditable(true);
				}else {
					dpCashTextField.setText("");
					dpCashTextField.setEditable(false);
				}
			}
		});

		transferChkbox = new javax.swing.JCheckBox();
		transferChkbox.setBounds(235, 160, 95, 20);
		transferChkbox.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				if (transferChkbox.isSelected()){
					dpTransferTextField.setEditable(true);
				}
				else {
					dpTransferTextField.setText("");
					dpTransferTextField.setEditable(false);
				}
			}
		});
		
		buttonPanel = new javax.swing.JPanel();
		buttonPanel.setBounds(10, 530, 350, 45);
		resetButton = new javax.swing.JButton();
		resetButton.setBounds(95, 10, 75, 25);
		
		resetButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				frameTransactionController.clearField();
			}
		});
		
		tundaButton = new javax.swing.JButton();
		tundaButton.setBounds(180, 10, 75, 25);
		bayarButton = new javax.swing.JButton();
		bayarButton.setBounds(265, 10, 75, 25);
		bayarButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				Transaction transaction = new Transaction();
				transaction.setIdTransaction(transactionIdLabel.getText());
		    	transaction.setIdCostumer(getCustomerId());
		    	transaction.setIdLens(getLensId());
		    	transaction.setIdFrame(getFrameId());
		    	transaction.setName(nameTxt.getText());
		    	transaction.setTelp(teleponTxt.getText());
		    	transaction.setHP(mobileTxt.getText());
		    	transaction.setBirthDate(bodTxt.getDate());
				transaction.setTransactionDate(new Date());
		    	transaction.setLens(lensTxt.getText());
		    	transaction.setLensColor(lensColorTxt.getText());
		    	transaction.setFrame(frameTxt.getText());
		    	transaction.setDesc(frameDescText.getText());
				frameTransactionController.bayar(transaction);
			}
		});

		exitBtn.setMnemonic('k');

		setBorder(javax.swing.BorderFactory.createEtchedBorder());
		setClosable(true);
		setIconifiable(true);
		setTitle("Transaksi Penjualan Frame dan Lensa");
		setToolTipText("");

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel1.setOpaque(false);

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel2.setOpaque(false);

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Id Transaksi");

		transactionIdLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
		transactionIdLabel.setForeground(new java.awt.Color(255, 255, 255));
		transactionIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		transactionIdLabel.setToolTipText("");

		jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12));
		jLabel26.setForeground(new java.awt.Color(255, 255, 255));
		jLabel26.setText("Tanggal");

		dateLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
		dateLabel.setForeground(new java.awt.Color(255, 255, 255));
		
		dateLabel.setText(sdf.format(new Date()));

		customerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		customerPanel.setOpaque(false);

		nameTxt.setToolTipText("");
		nameTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nameTxtActionPerformed(evt);
			}
		});
		
		nameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTxtMouseClicked(evt);
            }
        });

		nameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		nameLabel.setForeground(new java.awt.Color(255, 255, 255));
		nameLabel.setText("Nama");
		nameLabel.setPreferredSize(new java.awt.Dimension(75, 15));

		teleponLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
		teleponLabel.setForeground(new java.awt.Color(255, 255, 255));
		teleponLabel.setText("Telepon");
		teleponLabel.setPreferredSize(new java.awt.Dimension(75, 15));

		teleponTxt.setToolTipText("");
		teleponTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				phoneTxtActionPerformed(evt);
			}
		});

		bodLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		bodLabel.setForeground(new java.awt.Color(255, 255, 255));
		bodLabel.setText("HUT");
		bodLabel.setPreferredSize(new java.awt.Dimension(75, 15));

		hpLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		hpLabel.setForeground(new java.awt.Color(255, 255, 255));
		hpLabel.setText("HP");
		hpLabel.setPreferredSize(new java.awt.Dimension(75, 15));

		mobileTxt.setToolTipText("");
		mobileTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mobileTxtActionPerformed(evt);
			}
		});

		lensPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		lensPanel.setOpaque(false);

		lensLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		lensLabel.setForeground(new java.awt.Color(255, 255, 255));
		lensLabel.setText("Lensa");
		lensLabel.setPreferredSize(new java.awt.Dimension(75, 15));

		lensTxt.setToolTipText("");
		lensTxt.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				lensTxtMousePressed(evt);
			}
		});
		lensTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				lensTxtActionPerformed(evt);
			}
		});

		lensColorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		lensColorLabel.setForeground(new java.awt.Color(255, 255, 255));
		lensColorLabel.setText("Warna");
		lensColorLabel.setPreferredSize(new java.awt.Dimension(75, 15));

		lensColorTxt.setToolTipText("");
		lensColorTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				colorTxtActionPerformed(evt);
			}
		});

		jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("O.D. Sph.");
		jLabel10.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("Cly");
		jLabel11.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("Axis");
		jLabel12.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("O.S. Sph.");
		jLabel13.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setText("Cly");
		jLabel14.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("Axis");
		jLabel15.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel24.setForeground(new java.awt.Color(255, 255, 255));
		jLabel24.setText("Addition");
		jLabel24.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel16.setForeground(new java.awt.Color(255, 255, 255));
		jLabel16.setText("PD.");
		jLabel16.setPreferredSize(new java.awt.Dimension(75, 15));

		pdTxt.setToolTipText("");
		pdTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pdTxtActionPerformed(evt);
			}
		});

		/*String[] sph = new String[121];

        int x = 1525;
		for (int i = 0; i < 121; i++) {
			x = x-25;
			if (Math.signum(x)==1) {
				sph[i] = "+"+x;
			}
			else if(Math.signum(x)==-1) {
				sph[i] = ""+x;
			}
			else {
				sph[i] = ""+x;
			}
		}*/

		odSphCmbox = new JComboBox(Main.sph);
		odSphCmbox.setBounds(97, 75, 100, 20);
		odSphCmbox.setSelectedIndex(80);

		osSphCmbox = new JComboBox(Main.sph);
		osSphCmbox.setBounds(97, 106, 100, 20);
		osSphCmbox.setSelectedIndex(80);

		/*String[] cly = new String[25]; 

        int y = 0;

        for (int i = 0; i < cly.length; i++) {
        	y = y + 25;
			cly[i] = "-"+y;
		}*/

		odClyCmbox = new JComboBox(Main.cly);
		odClyCmbox.setBounds(245, 75, 100, 20);

		osClyCmbox = new JComboBox(Main.cly);
		osClyCmbox.setBounds(245, 106, 100, 20);

		/*String[] add = new String[9];
        int b = 75;

        for (int i = 0; i < add.length; i++) {
			b = b + 25;
			add[i] = "+"+b;
		}*/

		addBox = new JComboBox(Main.add);
		addBox.setBounds(97, 137, 100, 20);

		odAxisTextfield = new JTextField();
		odAxisTextfield.setBounds(419, 75, 104, 20);
		odAxisTextfield.setColumns(10);

		osAxisTextfield = new JTextField();
		osAxisTextfield.setBounds(419, 106, 104, 20);
		osAxisTextfield.setColumns(10);

		framePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		framePanel.setOpaque(false);

		frameTxt.setToolTipText("");
		frameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				frameTxtMousePressed(evt);
			}
		});
		frameTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				frameTxtActionPerformed(evt);
			}
		});

		frameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		frameLabel.setForeground(new java.awt.Color(255, 255, 255));
		frameLabel.setText("Frame");
		frameLabel.setPreferredSize(new java.awt.Dimension(75, 15));

		frameDescLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		frameDescLabel.setForeground(new java.awt.Color(255, 255, 255));
		frameDescLabel.setText("Keterangan");
		frameDescLabel.setPreferredSize(new java.awt.Dimension(75, 15));

		frameDescText.setColumns(20);
		frameDescText.setLineWrap(true);
		frameDescText.setRows(5);
		jScrollPane1.setViewportView(frameDescText);
		jPanel2.setLayout(null);
		jPanel2.add(jLabel2);
		jPanel2.add(transactionIdLabel);
		jPanel2.add(jLabel26);
		jPanel2.add(dateLabel);
		framePanel.setLayout(null);
		framePanel.add(frameLabel);
		framePanel.add(frameTxt);
		framePanel.add(frameDescLabel);
		framePanel.add(jScrollPane1);
		customerPanel.setLayout(null);
		customerPanel.add(nameLabel);
		customerPanel.add(nameTxt);
		customerPanel.add(bodLabel);
		customerPanel.add(bodTxt);
		customerPanel.add(teleponLabel);
		customerPanel.add(hpLabel);
		customerPanel.add(teleponTxt);
		customerPanel.add(mobileTxt);
		lensPanel.setLayout(null);
		lensPanel.add(lensLabel);
		lensPanel.add(lensTxt);
		lensPanel.add(lensColorLabel);
		lensPanel.add(lensColorTxt);
		lensPanel.add(jLabel10);
		lensPanel.add(odSphCmbox);
		lensPanel.add(jLabel11);
		lensPanel.add(odClyCmbox);
		lensPanel.add(jLabel12);
		lensPanel.add(jLabel13);
		lensPanel.add(osSphCmbox);
		lensPanel.add(jLabel14);
		lensPanel.add(osClyCmbox);
		lensPanel.add(jLabel15);
		lensPanel.add(jLabel24);
		lensPanel.add(addBox);
		lensPanel.add(jLabel16);
		lensPanel.add(pdTxt);
		lensPanel.add(odAxisTextfield);
		lensPanel.add(osAxisTextfield);

		jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel7.setOpaque(false);

		jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel6.setOpaque(false);

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Harga Lensa");
		jLabel5.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel18.setForeground(new java.awt.Color(255, 255, 255));
		jLabel18.setText("Harga Frame");
		jLabel18.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel20.setForeground(new java.awt.Color(255, 255, 255));
		jLabel20.setText("Diskon");
		jLabel20.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel21.setForeground(new java.awt.Color(255, 255, 255));
		jLabel21.setText("Jumlah");
		jLabel21.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel23.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel23.setForeground(new java.awt.Color(255, 255, 255));
		jLabel23.setText("Sisa");
		jLabel23.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Tipe \r\nPembayaran");

		cashChkbox.setText("Cash");

		transferChkbox.setText("Transfer");

		final JCheckBox instansiChkbox = new JCheckBox();
		instansiChkbox.setBounds(235, 130, 95, 20);
		instansiChkbox.setText("Instansi");
		
		instansiChkbox.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				if (instansiChkbox.isSelected()) {
					noLegalisasiTextField.setEditable(true);
					dpInstansiTextField.setEditable(true);
				}
				else {
					noLegalisasiTextField.setText("");
					noLegalisasiTextField.setEditable(false);
					dpInstansiTextField.setText("");
					dpInstansiTextField.setEditable(false);
				}
			}
		});

		String[] kartu = {"Pilih","DEBIT","KREDIT"};
		final JComboBox kartuCmb = new JComboBox(kartu);
		kartuCmb.setSelectedIndex(0);
		kartuCmb.setBounds(130, 160, 95, 20);

		kartuCmb.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (kartuCmb.getSelectedIndex()!=0) {
					noTraceTextField.setEditable(true);
					noKartuTextField.setEditable(true);
					dpKartuTextField.setEditable(true);
				}
				else {
					noTraceTextField.setText("");
					noTraceTextField.setEditable(false);
					noKartuTextField.setText("");
					noKartuTextField.setEditable(false);
					dpKartuTextField.setText("");
					dpKartuTextField.setEditable(false);
				}
			}
		});

		buttonPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		buttonPanel.setOpaque(false);

		resetButton.setText("Reset");
		tundaButton.setText("Tunda");
		bayarButton.setText("Bayar");
		
		jPanel6.setLayout(null);
		jPanel6.add(jLabel5);
		jPanel6.add(lensPriceTextField);
		jPanel6.add(jLabel18);
		jPanel6.add(framePriceTextField);
		jPanel6.add(jLabel20);
		jPanel6.add(diskonTextField);
		jPanel6.add(jLabel23);
		jPanel6.add(jLabel21);
		jPanel6.add(jLabel1);
		jPanel6.add(totalBayarTextField);
		jPanel6.add(cashChkbox);
		jPanel6.add(kartuCmb);
		jPanel6.add(instansiChkbox);
		jPanel6.add(transferChkbox);
		jPanel6.add(sisaTextField);

		JPanel cashPanel = new JPanel();
		cashPanel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, Color.WHITE, null));
		cashPanel.setForeground(Color.WHITE);
		cashPanel.setBounds(10, 190, 327, 40);
		cashPanel.setOpaque(false);
		jPanel6.add(cashPanel);
		cashPanel.setLayout(null);
		jLabel28 = new javax.swing.JLabel();
		jLabel28.setBounds(10, 10, 90, 20);
		cashPanel.add(jLabel28);

		jLabel28.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel28.setForeground(Color.WHITE);
		jLabel28.setText("DP Cash");

		dpCashTextField = new JTextField();
		dpCashTextField.setBounds(117, 10, 200, 20);
		dpCashTextField.setEditable(false);
		
		dpCashTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		cashPanel.add(dpCashTextField);

		kartuPanel = new JPanel();
		kartuPanel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
		kartuPanel.setBounds(10, 240, 327, 100);
		kartuPanel.setOpaque(false);
		jPanel6.add(kartuPanel);
		kartuPanel.setLayout(null);
		jLabel29 = new javax.swing.JLabel();
		jLabel29.setBounds(10, 10, 90, 20);
		kartuPanel.add(jLabel29);

		jLabel29.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel29.setForeground(Color.WHITE);
		jLabel29.setText("No Kartu");

		noKartuTextField = new JTextField();
		noKartuTextField.setBounds(117, 10, 200, 20);
		noKartuTextField.setEditable(false);
		kartuPanel.add(noKartuTextField);
		jLabel30 = new javax.swing.JLabel();
		jLabel30.setBounds(10, 40, 90, 20);
		kartuPanel.add(jLabel30);

		jLabel30.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel30.setForeground(Color.WHITE);
		jLabel30.setText("Trace No");
		noTraceTextField = new javax.swing.JTextField();
		noTraceTextField.setBounds(117, 40, 200, 20);
		noTraceTextField.setEditable(false);
		kartuPanel.add(noTraceTextField);

		dpKartuTextField = new JTextField();
		dpKartuTextField.setBounds(117, 70, 200, 20);
		dpKartuTextField.setEditable(false);
		
		dpKartuTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		kartuPanel.add(dpKartuTextField);

		JLabel lblDpKartu = new JLabel();
		lblDpKartu.setBounds(10, 70, 90, 20);
		kartuPanel.add(lblDpKartu);
		lblDpKartu.setText("Dp Kartu");
		lblDpKartu.setForeground(Color.WHITE);
		lblDpKartu.setFont(new Font("Tahoma", Font.BOLD, 12));

		instansiLabel = new JPanel();
		instansiLabel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
		instansiLabel.setBounds(10, 350, 327, 70);
		instansiLabel.setOpaque(false);
		jPanel6.add(instansiLabel);
		instansiLabel.setLayout(null);

		JLabel lblNoLegalisasi = new JLabel();
		lblNoLegalisasi.setBounds(10, 10, 90, 20);
		instansiLabel.add(lblNoLegalisasi);
		lblNoLegalisasi.setText("No. Legalisasi");
		lblNoLegalisasi.setForeground(Color.WHITE);
		lblNoLegalisasi.setFont(new Font("Tahoma", Font.BOLD, 12));
		noLegalisasiTextField = new javax.swing.JTextField();
		noLegalisasiTextField.setBounds(117, 10, 200, 20);
		noLegalisasiTextField.setEditable(false);
		instansiLabel.add(noLegalisasiTextField);
		dpInstansiTextField = new javax.swing.JTextField();
		dpInstansiTextField.setBounds(117, 40, 200, 20);
		dpInstansiTextField.setEditable(false);
		
		dpInstansiTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		instansiLabel.add(dpInstansiTextField);
		jLabel22 = new javax.swing.JLabel();
		jLabel22.setBounds(10, 40, 90, 20);
		instansiLabel.add(jLabel22);

		jLabel22.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel22.setForeground(Color.WHITE);
		jLabel22.setText("DP Instansi");
		jLabel22.setPreferredSize(new java.awt.Dimension(75, 15));

		transferPanel = new JPanel();
		transferPanel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
		transferPanel.setBounds(10, 430, 327, 40);
		transferPanel.setOpaque(false);
		jPanel6.add(transferPanel);
		transferPanel.setLayout(null);

		JLabel transferLbl = new JLabel();
		transferLbl.setBounds(10, 10, 90, 20);
		transferPanel.add(transferLbl);
		transferLbl.setText("Transfer");
		transferLbl.setPreferredSize(new Dimension(75, 15));
		transferLbl.setForeground(Color.WHITE);
		transferLbl.setFont(new Font("Tahoma", Font.BOLD, 12));
		dpTransferTextField = new javax.swing.JTextField();
		dpTransferTextField.setBounds(117, 10, 200, 20);
		dpTransferTextField.setEditable(false);
		
		dpTransferTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		transferPanel.add(dpTransferTextField);
		jPanel7.setLayout(null);
		jPanel7.setBounds(580, 10, 370, 585);
		jPanel7.add(jPanel6);
		jPanel7.add(buttonPanel);
		buttonPanel.setLayout(null);
		buttonPanel.add(resetButton);
		buttonPanel.add(tundaButton);
		buttonPanel.add(bayarButton);
		
		JButton newButton = new JButton();
		newButton.setText("Baru");
		newButton.setBounds(10, 10, 75, 25);
		
		newButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				frameTransactionController.createNewTransaction();
			}
		});
		
		buttonPanel.add(newButton);
		jPanel1.setLayout(null);
		jPanel1.setBounds(10, 10, 560, 585);
		jPanel1.add(jPanel2);
		jPanel1.add(framePanel);
		jPanel1.add(lensPanel);
		jPanel1.add(customerPanel);

		getContentPane().add(panel1, null);
		panel1.setLayout(null);
		panel1.setSize(950,605);
		panel1.add(jPanel1);
		panel1.add(jPanel7);

		pack();
	}

	public javax.swing.JTextField getDpTransferTextField() {
		return dpTransferTextField;
	}

	public void setDpTransferTextField(javax.swing.JTextField dpTransferTextField) {
		this.dpTransferTextField = dpTransferTextField;
	}

	public javax.swing.JTextField getDpInstansiTextField() {
		return dpInstansiTextField;
	}

	public void setDpInstansiTextField(javax.swing.JTextField dpInstansiTextField) {
		this.dpInstansiTextField = dpInstansiTextField;
	}

	public javax.swing.JTextField getNoLegalisasiTextField() {
		return noLegalisasiTextField;
	}

	public void setNoLegalisasiTextField(javax.swing.JTextField noLegalisasiTextField) {
		this.noLegalisasiTextField = noLegalisasiTextField;
	}

	public JTextField getDpKartuTextField() {
		return dpKartuTextField;
	}

	public void setDpKartuTextField(JTextField dpKartuTextField) {
		this.dpKartuTextField = dpKartuTextField;
	}

	public javax.swing.JTextField getNoTraceTextField() {
		return noTraceTextField;
	}

	public void setNoTraceTextField(javax.swing.JTextField noTraceTextField) {
		this.noTraceTextField = noTraceTextField;
	}

	public JTextField getNoKartuTextField() {
		return noKartuTextField;
	}

	public void setNoKartuTextField(JTextField noKartuTextField) {
		this.noKartuTextField = noKartuTextField;
	}

	public JTextField getDpCashTextField() {
		return dpCashTextField;
	}

	public void setDpCashTextField(JTextField dpCashTextField) {
		this.dpCashTextField = dpCashTextField;
	}

	public javax.swing.JCheckBox getCashChkbox() {
		return cashChkbox;
	}

	public void setCashChkbox(javax.swing.JCheckBox cashChkbox) {
		this.cashChkbox = cashChkbox;
	}

	public javax.swing.JTextArea getDescTxt() {
		return frameDescText;
	}

	public void setDescTxt(javax.swing.JTextArea descTxt) {
		this.frameDescText = descTxt;
	}

	public void setFrameTxt(javax.swing.JTextField frameTxt) {
		this.frameTxt = frameTxt;
	}

	public JTextField getOsAxisTextfield() {
		return osAxisTextfield;
	}

	public void setOsAxisTextfield(JTextField osAxisTextfield) {
		this.osAxisTextfield = osAxisTextfield;
	}

	public JComboBox getOsClyCmbox() {
		return osClyCmbox;
	}

	public void setOsClyCmbox(JComboBox osClyCmbox) {
		this.osClyCmbox = osClyCmbox;
	}

	public JComboBox getOsSphCmbox() {
		return osSphCmbox;
	}

	public void setOsSphCmbox(JComboBox osSphCmbox) {
		this.osSphCmbox = osSphCmbox;
	}

	public JTextField getOdAxisTextfield() {
		return odAxisTextfield;
	}

	public void setOdAxisTextfield(JTextField odAxisTextfield) {
		this.odAxisTextfield = odAxisTextfield;
	}

	public JComboBox getOdClyCmbox() {
		return odClyCmbox;
	}

	public void setOdClyCmbox(JComboBox odClyCmbox) {
		this.odClyCmbox = odClyCmbox;
	}

	public JComboBox getOdSphCmbox() {
		return odSphCmbox;
	}

	public void setOdSphCmbox(JComboBox odSphCmbox) {
		this.odSphCmbox = odSphCmbox;
	}

	protected void count() {
		int lens = 0;
		int frame = 0;
		int diskon = 0;
		int total = 0;
		
		int dpCash = 0;
		int dpKartu = 0;
		int dpInstansi = 0;
		int dpTransfer = 0;
		int sisa = 0;
		
		System.out.println();
		
		if (!"".equals(lensPriceTextField.getText())) lens = Integer.parseInt(lensPriceTextField.getText());
		else lens = 0;
		if (!"".equals(framePriceTextField.getText())) frame = Integer.parseInt(framePriceTextField.getText());
		else frame = 0;
		if (!"".equals(diskonTextField.getText())) diskon = Integer.parseInt(diskonTextField.getText());
		else diskon = 0;
		
		if (!"".equals(dpCashTextField.getText())) dpCash = Integer.parseInt(dpCashTextField.getText());
		else dpCash = 0;
		if (!"".equals(dpKartuTextField.getText())) dpKartu = Integer.parseInt(dpKartuTextField.getText());
		else dpKartu = 0;
		if (!"".equals(dpInstansiTextField.getText())) dpInstansi = Integer.parseInt(dpInstansiTextField.getText());
		else dpInstansi = 0;
		if (!"".equals(dpTransferTextField.getText())) dpTransfer = Integer.parseInt(dpTransferTextField.getText());
		else dpTransfer = 0;
		
		total = (lens+frame)-diskon;
		sisa = total - (dpCash+dpKartu+dpInstansi+dpTransfer);
		
		totalBayarTextField.setText(""+total);
		sisaTextField.setText(""+sisa);
	}

	private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {
		
	}

	private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {
		
	}

	private void mobileTxtActionPerformed(java.awt.event.ActionEvent evt) {
		
	}

	private void lensTxtActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void colorTxtActionPerformed(java.awt.event.ActionEvent evt) {
		
	}

	private void pdTxtActionPerformed(java.awt.event.ActionEvent evt) {
		
	}

	private void frameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameTxtActionPerformed

	}

	private void lensTxtMousePressed(java.awt.event.MouseEvent evt) {
		frameTransactionController.show(this, new LensDialog(this));
	}

	private void frameTxtMousePressed(java.awt.event.MouseEvent evt) {
		frameTransactionController.show(this, new FrameDialog(this));
	}
	
	private void nameTxtMouseClicked(java.awt.event.MouseEvent evt) {                                     
        frameTransactionController.show(this, new CustomerDialog(this));
    }
	
	private javax.swing.JTextField diskonTextField;
	private javax.swing.JTextField sisaTextField;
	private com.toedter.calendar.JDateChooser bodTxt;
	private javax.swing.JTextField lensColorTxt;
	private javax.swing.JTextArea frameDescText;
	private javax.swing.JTextField totalBayarTextField;
	private javax.swing.JButton exitBtn;
	private javax.swing.JTextField framePriceTextField;
	private javax.swing.JTextField frameTxt;
	private javax.swing.JTextField dpTransferTextField;
	private javax.swing.JButton resetButton;
	private javax.swing.JButton tundaButton;
	private javax.swing.JButton bayarButton;
	private javax.swing.JCheckBox cashChkbox;
	private javax.swing.JCheckBox transferChkbox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel frameLabel;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel frameDescLabel;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel transactionIdLabel;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel dateLabel;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel teleponLabel;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel bodLabel;
	private javax.swing.JLabel hpLabel;
	private javax.swing.JLabel lensLabel;
	private javax.swing.JLabel lensColorLabel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel customerPanel;
	private javax.swing.JPanel lensPanel;
	private javax.swing.JPanel framePanel;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel buttonPanel;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField noTraceTextField;
	private javax.swing.JTextField noLegalisasiTextField;
	private javax.swing.JTextField dpInstansiTextField;
	private javax.swing.JTextField lensPriceTextField;
	private javax.swing.JTextField lensTxt;
	private javax.swing.JTextField mobileTxt;
	private javax.swing.JTextField nameTxt;
	private indooptik.utility.Panel panel1;
	private javax.swing.JTextField pdTxt;
	private javax.swing.JTextField teleponTxt;
	private JTextField dpCashTextField;
	private JTextField noKartuTextField;
	private JTextField odAxisTextfield;
	private JTextField osAxisTextfield;
	private JTextField dpKartuTextField;
	private JPanel kartuPanel;
	private JPanel instansiLabel;
	private JPanel transferPanel;
	private JComboBox odSphCmbox;
	private JComboBox osSphCmbox;
	private JComboBox odClyCmbox;
	private JComboBox osClyCmbox;
	private JComboBox addBox;

	@Override
	public void insertUpdate(DocumentEvent e) {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	@Override
	public void removeUpdate(DocumentEvent e) {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	@Override
	public void changedUpdate(DocumentEvent e) {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * @param frameTransactionController the frameTransactionController to set
	 */
	public void setFrameTransactionController(FrameTransactionController frameTransactionController) {
		this.frameTransactionController = frameTransactionController;
	}

	/**
	 * @return the additionTxt
	 */
	/*public javax.swing.JTextField getAdditionTxt() {
        return additionTxt;
    }*/

	/**
	 * @return the amountTxt
	 */
	public javax.swing.JTextField getAmountTxt() {
		return diskonTextField;
	}

	/**
	 * @return the balanceTxt
	 */
	public javax.swing.JTextField getBalanceTxt() {
		return sisaTextField;
	}

	/**
	 * @return the bodTxt
	 */
	public com.toedter.calendar.JDateChooser getBodTxt() {
		return bodTxt;
	}

	/**
	 * @return the colorTxt
	 */
	public javax.swing.JTextField getColorTxt() {
		return lensColorTxt;
	}

	/**
	 * @return the dpTxt
	 */
	public javax.swing.JTextField getDpTxt() {
		return totalBayarTextField;
	}

	/**
	 * @return the framePriceTxt
	 */
	public javax.swing.JTextField getFramePriceTxt() {
		return framePriceTextField;
	}

	/**
	 * @return the frameTxt
	 */
	public javax.swing.JTextField getFrameTxt() {
		return frameTxt;
	}

	/**
	 * @return the instituteTxt
	 */
	public javax.swing.JTextField getInstituteTxt() {
		return dpTransferTextField;
	}

	/**
	 * @return the lensPriceTxt
	 */
	public javax.swing.JTextField getLensPriceTxt() {
		return lensPriceTextField;
	}

	/**
	 * @return the lensTxt
	 */
	public javax.swing.JTextField getLensTxt() {
		return lensTxt;
	}

	/**
	 * @return the mobileTxt
	 */
	public javax.swing.JTextField getMobileTxt() {
		return mobileTxt;
	}

	/**
	 * @return the nameTxt
	 */
	public javax.swing.JTextField getNameTxt() {
		return nameTxt;
	}

	public javax.swing.JTextField getPdTxt() {
		return pdTxt;
	}

	public javax.swing.JTextField getPhoneTxt() {
		return teleponTxt;
	}
	
	public javax.swing.JLabel getTransactionIdLabel() {
		return transactionIdLabel;
	}

	public void setTransactionIdLabel(javax.swing.JLabel transactionIdLabel) {
		this.transactionIdLabel = transactionIdLabel;
	}
}
