/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indooptik.internalframe;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.EtchedBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import indooptik.controller.FrameTransactionController;
import indooptik.jdialog.CustomerDialog;
import indooptik.jdialog.FrameDialog;
import indooptik.jdialog.LensDialog;
import indooptik.main.Main;
import indooptik.utility.SystemID;
import javax.swing.JButton;

/**
 *
 * @author Yoeda H
 */
public class FrameTransactionInternalFrame extends javax.swing.JInternalFrame implements DocumentListener{    

	private FrameTransactionController frameTransactionController;
	/**
	 * Creates new form DisplayTable
	 */
	public FrameTransactionInternalFrame() {
		initComponents();
	}    

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		exitBtn = new javax.swing.JButton();
		panel1 = new indooptik.utility.Panel();
		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBounds(0, 10, 560, 560);
		jPanel2 = new javax.swing.JPanel();
		jPanel2.setBounds(10, 10, 540, 71);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setBounds(12, 13, 75, 15);
		jLabel25 = new javax.swing.JLabel();
		jLabel25.setBounds(93, 13, 75, 15);
		jLabel26 = new javax.swing.JLabel();
		jLabel26.setBounds(309, 13, 75, 15);
		dateLabel = new javax.swing.JLabel();
		dateLabel.setBounds(390, 13, 75, 15);
		jPanel3 = new javax.swing.JPanel();
		jPanel3.setBounds(10, 92, 540, 130);
		nameTxt = new javax.swing.JTextField();
		nameTxt.setBounds(97, 13, 250, 20);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setBounds(10, 10, 75, 20);
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setBounds(12, 40, 75, 20);
		phoneTxt = new javax.swing.JTextField();
		phoneTxt.setBounds(97, 42, 250, 20);
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setBounds(12, 100, 75, 20);
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setBounds(12, 70, 75, 20);
		mobileTxt = new javax.swing.JTextField();
		mobileTxt.setBounds(97, 73, 250, 20);
		bodTxt = new com.toedter.calendar.JDateChooser();
		bodTxt.setBounds(97, 101, 100, 20);
		jPanel4 = new javax.swing.JPanel();
		jPanel4.setBounds(10, 233, 540, 170);
		jLabel8 = new javax.swing.JLabel();
		jLabel8.setBounds(10, 10, 75, 20);
		lensTxt = new javax.swing.JTextField();
		lensTxt.setBounds(97, 13, 250, 20);
		jLabel9 = new javax.swing.JLabel();
		jLabel9.setBounds(12, 46, 75, 20);
		colorTxt = new javax.swing.JTextField();
		colorTxt.setBounds(97, 44, 250, 20);
		jLabel10 = new javax.swing.JLabel();
		jLabel10.setBounds(12, 77, 75, 20);
		jLabel11 = new javax.swing.JLabel();
		jLabel11.setBounds(205, 77, 35, 15);
		jLabel12 = new javax.swing.JLabel();
		jLabel12.setBounds(378, 77, 35, 15);
		jLabel13 = new javax.swing.JLabel();
		jLabel13.setBounds(12, 108, 75, 20);
		jLabel14 = new javax.swing.JLabel();
		jLabel14.setBounds(205, 108, 35, 15);
		jLabel15 = new javax.swing.JLabel();
		jLabel15.setBounds(378, 108, 35, 15);
		jLabel24 = new javax.swing.JLabel();
		jLabel24.setBounds(12, 139, 75, 20);
		jLabel16 = new javax.swing.JLabel();
		jLabel16.setBounds(205, 142, 35, 15);
		pdTxt = new javax.swing.JTextField();
		pdTxt.setBounds(245, 140, 100, 20);
		jPanel5 = new javax.swing.JPanel();
		jPanel5.setBounds(10, 414, 540, 160);
		frameTxt = new javax.swing.JTextField();
		frameTxt.setBounds(97, 13, 250, 20);
		jLabel17 = new javax.swing.JLabel();
		jLabel17.setBounds(10, 10, 75, 20);
		jLabel19 = new javax.swing.JLabel();
		jLabel19.setBounds(10, 40, 75, 20);
		jScrollPane1 = new javax.swing.JScrollPane();
		jScrollPane1.setBounds(97, 44, 426, 96);
		descTxt = new javax.swing.JTextArea();
		jPanel7 = new javax.swing.JPanel();
		jPanel7.setBounds(580, 0, 370, 600);
		jPanel6 = new javax.swing.JPanel();
		jPanel6.setBounds(10, 10, 350, 510);
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setBounds(10, 10, 80, 20);
		lensPriceTextField = new javax.swing.JTextField();
		lensPriceTextField.setBounds(130, 10, 200, 20);
		
		lensPriceTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		jLabel18 = new javax.swing.JLabel();
		jLabel18.setBounds(10, 40, 80, 20);
		framePriceTextField = new javax.swing.JTextField();
		framePriceTextField.setBounds(130, 40, 200, 20);
		
		framePriceTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		jLabel20 = new javax.swing.JLabel();
		jLabel20.setBounds(10, 70, 80, 20);
		diskonTextField = new javax.swing.JTextField();
		diskonTextField.setBounds(130, 70, 200, 20);
		
		diskonTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		jLabel21 = new javax.swing.JLabel();
		jLabel21.setBounds(10, 100, 80, 20);
		totalBayarTextField = new javax.swing.JTextField();
		totalBayarTextField.setBounds(130, 100, 200, 20);
		
		jLabel23 = new javax.swing.JLabel();
		jLabel23.setBounds(22, 480, 75, 15);
		sisaTextField = new javax.swing.JTextField();
		sisaTextField.setBounds(130, 480, 200, 20);
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setBounds(12, 130, 100, 50);
		cashChkbox = new javax.swing.JCheckBox();
		cashChkbox.setBounds(130, 130, 95, 20);

		cashChkbox.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (cashChkbox.isSelected()) {
					dpCashTextField.setEditable(true);
				}else {
					dpCashTextField.setText("");
					dpCashTextField.setEditable(false);
				}
			}
		});

		transferChkbox = new javax.swing.JCheckBox();
		transferChkbox.setBounds(235, 160, 95, 20);
		
		transferChkbox.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				if (transferChkbox.isSelected()){
					dpTransferTextField.setEditable(true);
				}
				else {
					dpTransferTextField.setText("");
					dpTransferTextField.setEditable(false);
				}
			}
		});
		
		jPanel8 = new javax.swing.JPanel();
		jPanel8.setBounds(10, 530, 350, 45);
		resetButton = new javax.swing.JButton();
		resetButton.setBounds(95, 10, 75, 25);
		
		resetButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				createNewTransaction();
			}
		});
		
		tundaButton = new javax.swing.JButton();
		tundaButton.setBounds(180, 10, 75, 25);
		bayarButton = new javax.swing.JButton();
		bayarButton.setBounds(265, 10, 75, 25);
		bayarButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				System.out.println("yahoo");
			}
		});

		exitBtn.setMnemonic('k');

		setBorder(javax.swing.BorderFactory.createEtchedBorder());
		setClosable(true);
		setIconifiable(true);
		setTitle("Transaksi Penjualan Lensa dan Frame");
		setToolTipText("");

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel1.setOpaque(false);

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel2.setOpaque(false);

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Id Transaksi");

		jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel25.setForeground(new java.awt.Color(255, 255, 255));
		jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel25.setToolTipText("");

		jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel26.setForeground(new java.awt.Color(255, 255, 255));
		jLabel26.setText("Tanggal");

		dateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		dateLabel.setForeground(new java.awt.Color(255, 255, 255));
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		dateLabel.setText(sdf.format(new Date()));

		jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel3.setOpaque(false);

		nameTxt.setToolTipText("");
		nameTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nameTxtActionPerformed(evt);
			}
		});
		
		nameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTxtMouseClicked(evt);
            }
        });

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Nama");
		jLabel3.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("Telp");
		jLabel4.setPreferredSize(new java.awt.Dimension(75, 15));

		phoneTxt.setToolTipText("");
		phoneTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				phoneTxtActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("HUT");
		jLabel6.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("HP");
		jLabel7.setPreferredSize(new java.awt.Dimension(75, 15));

		mobileTxt.setToolTipText("");
		mobileTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mobileTxtActionPerformed(evt);
			}
		});

		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel4.setOpaque(false);

		jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("Lensa");
		jLabel8.setPreferredSize(new java.awt.Dimension(75, 15));

		lensTxt.setToolTipText("");
		lensTxt.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				lensTxtMousePressed(evt);
			}
		});
		lensTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				lensTxtActionPerformed(evt);
			}
		});

		jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("Warna");
		jLabel9.setPreferredSize(new java.awt.Dimension(75, 15));

		colorTxt.setToolTipText("");
		colorTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				colorTxtActionPerformed(evt);
			}
		});

		jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("O.D. Sph.");
		jLabel10.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("Cly");
		jLabel11.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("Axis");
		jLabel12.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("O.S. Sph.");
		jLabel13.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setText("Cly");
		jLabel14.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("Axis");
		jLabel15.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel24.setForeground(new java.awt.Color(255, 255, 255));
		jLabel24.setText("Addition");
		jLabel24.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel16.setForeground(new java.awt.Color(255, 255, 255));
		jLabel16.setText("PD.");
		jLabel16.setPreferredSize(new java.awt.Dimension(75, 15));

		pdTxt.setToolTipText("");
		pdTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pdTxtActionPerformed(evt);
			}
		});

		/*String[] sph = new String[121];

        int x = 1525;
		for (int i = 0; i < 121; i++) {
			x = x-25;
			if (Math.signum(x)==1) {
				sph[i] = "+"+x;
			}
			else if(Math.signum(x)==-1) {
				sph[i] = ""+x;
			}
			else {
				sph[i] = ""+x;
			}
		}*/

		JComboBox odSphCmbox = new JComboBox(Main.sph);
		odSphCmbox.setBounds(97, 75, 100, 20);
		odSphCmbox.setSelectedIndex(80);

		JComboBox osSphCmbox = new JComboBox(Main.sph);
		osSphCmbox.setBounds(97, 106, 100, 20);
		osSphCmbox.setSelectedIndex(80);

		/*String[] cly = new String[25]; 

        int y = 0;

        for (int i = 0; i < cly.length; i++) {
        	y = y + 25;
			cly[i] = "-"+y;
		}*/

		JComboBox odClyCmbox = new JComboBox(Main.cly);
		odClyCmbox.setBounds(245, 75, 100, 20);

		JComboBox osClyCmbox = new JComboBox(Main.cly);
		osClyCmbox.setBounds(245, 106, 100, 20);

		/*String[] add = new String[9];
        int b = 75;

        for (int i = 0; i < add.length; i++) {
			b = b + 25;
			add[i] = "+"+b;
		}*/

		JComboBox addBox = new JComboBox(Main.add);
		addBox.setBounds(97, 137, 100, 20);

		textField_2 = new JTextField();
		textField_2.setBounds(419, 75, 104, 20);
		textField_2.setColumns(10);

		textField_3 = new JTextField();
		textField_3.setBounds(419, 106, 104, 20);
		textField_3.setColumns(10);

		jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel5.setOpaque(false);

		frameTxt.setToolTipText("");
		frameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				frameTxtMousePressed(evt);
			}
		});
		frameTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				frameTxtActionPerformed(evt);
			}
		});

		jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel17.setForeground(new java.awt.Color(255, 255, 255));
		jLabel17.setText("Frame");
		jLabel17.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(255, 255, 255));
		jLabel19.setText("Keterangan");
		jLabel19.setPreferredSize(new java.awt.Dimension(75, 15));

		descTxt.setColumns(20);
		descTxt.setLineWrap(true);
		descTxt.setRows(5);
		jScrollPane1.setViewportView(descTxt);
		jPanel2.setLayout(null);
		jPanel2.add(jLabel2);
		jPanel2.add(jLabel25);
		jPanel2.add(jLabel26);
		jPanel2.add(dateLabel);
		jPanel5.setLayout(null);
		jPanel5.add(jLabel17);
		jPanel5.add(frameTxt);
		jPanel5.add(jLabel19);
		jPanel5.add(jScrollPane1);
		jPanel3.setLayout(null);
		jPanel3.add(jLabel3);
		jPanel3.add(nameTxt);
		jPanel3.add(jLabel6);
		jPanel3.add(bodTxt);
		jPanel3.add(jLabel4);
		jPanel3.add(jLabel7);
		jPanel3.add(phoneTxt);
		jPanel3.add(mobileTxt);
		jPanel4.setLayout(null);
		jPanel4.add(jLabel8);
		jPanel4.add(lensTxt);
		jPanel4.add(jLabel9);
		jPanel4.add(colorTxt);
		jPanel4.add(jLabel10);
		jPanel4.add(odSphCmbox);
		jPanel4.add(jLabel11);
		jPanel4.add(odClyCmbox);
		jPanel4.add(jLabel12);
		jPanel4.add(jLabel13);
		jPanel4.add(osSphCmbox);
		jPanel4.add(jLabel14);
		jPanel4.add(osClyCmbox);
		jPanel4.add(jLabel15);
		jPanel4.add(jLabel24);
		jPanel4.add(addBox);
		jPanel4.add(jLabel16);
		jPanel4.add(pdTxt);
		jPanel4.add(textField_2);
		jPanel4.add(textField_3);

		jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel7.setOpaque(false);

		jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel6.setOpaque(false);

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Harga Lensa");
		jLabel5.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel18.setForeground(new java.awt.Color(255, 255, 255));
		jLabel18.setText("Harga Frame");
		jLabel18.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel20.setForeground(new java.awt.Color(255, 255, 255));
		jLabel20.setText("Diskon");
		jLabel20.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel21.setForeground(new java.awt.Color(255, 255, 255));
		jLabel21.setText("Jumlah");
		jLabel21.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel23.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel23.setForeground(new java.awt.Color(255, 255, 255));
		jLabel23.setText("Sisa");
		jLabel23.setPreferredSize(new java.awt.Dimension(75, 15));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Tipe \r\nPembayaran");

		cashChkbox.setText("Cash");

		transferChkbox.setText("Transfer");

		final JCheckBox instansiChkbox = new JCheckBox();
		instansiChkbox.setBounds(235, 130, 95, 20);
		instansiChkbox.setText("Instansi");
		
		instansiChkbox.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				if (instansiChkbox.isSelected()) {
					noLegalisasiTextField.setEditable(true);
					dpInstansiTextField.setEditable(true);
				}
				else {
					noLegalisasiTextField.setText("");
					noLegalisasiTextField.setEditable(false);
					dpInstansiTextField.setText("");
					dpInstansiTextField.setEditable(false);
				}
			}
		});

		String[] kartu = {"Pilih","DEBIT","KREDIT"};
		final JComboBox kartuCmbox = new JComboBox(kartu);
		kartuCmbox.setSelectedIndex(0);
		kartuCmbox.setBounds(130, 160, 95, 20);


		kartuCmbox.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (kartuCmbox.getSelectedIndex()!=0) {
					noTraceTextField.setEditable(true);
					noKartuTextField.setEditable(true);
					dpKartuTextField.setEditable(true);
				}
				else {
					noTraceTextField.setText("");
					noTraceTextField.setEditable(false);
					noKartuTextField.setText("");
					noKartuTextField.setEditable(false);
					dpKartuTextField.setText("");
					dpKartuTextField.setEditable(false);
				}
			}
		});

		jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel8.setOpaque(false);

		resetButton.setText("Reset");

		tundaButton.setText("Tunda");

		bayarButton.setText("Bayar");
		jPanel6.setLayout(null);
		jPanel6.add(jLabel5);
		jPanel6.add(lensPriceTextField);
		jPanel6.add(jLabel18);
		jPanel6.add(framePriceTextField);
		jPanel6.add(jLabel20);
		jPanel6.add(diskonTextField);
		jPanel6.add(jLabel23);
		jPanel6.add(jLabel21);
		jPanel6.add(jLabel1);
		jPanel6.add(totalBayarTextField);
		jPanel6.add(cashChkbox);
		jPanel6.add(kartuCmbox);
		jPanel6.add(instansiChkbox);
		jPanel6.add(transferChkbox);
		jPanel6.add(sisaTextField);

		JPanel cashPanel = new JPanel();
		cashPanel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, Color.WHITE, null));
		cashPanel.setForeground(Color.WHITE);
		cashPanel.setBounds(10, 190, 327, 40);
		cashPanel.setOpaque(false);
		jPanel6.add(cashPanel);
		cashPanel.setLayout(null);
		jLabel28 = new javax.swing.JLabel();
		jLabel28.setBounds(10, 10, 90, 20);
		cashPanel.add(jLabel28);

		jLabel28.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel28.setForeground(Color.WHITE);
		jLabel28.setText("DP Cash");

		dpCashTextField = new JTextField();
		dpCashTextField.setBounds(117, 10, 200, 20);
		dpCashTextField.setEditable(false);
		
		dpCashTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		cashPanel.add(dpCashTextField);

		kartuPanel = new JPanel();
		kartuPanel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
		kartuPanel.setBounds(10, 240, 327, 100);
		kartuPanel.setOpaque(false);
		jPanel6.add(kartuPanel);
		kartuPanel.setLayout(null);
		jLabel29 = new javax.swing.JLabel();
		jLabel29.setBounds(10, 10, 90, 20);
		kartuPanel.add(jLabel29);

		jLabel29.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel29.setForeground(Color.WHITE);
		jLabel29.setText("No Kartu");

		noKartuTextField = new JTextField();
		noKartuTextField.setBounds(117, 10, 200, 20);
		noKartuTextField.setEditable(false);
		kartuPanel.add(noKartuTextField);
		jLabel30 = new javax.swing.JLabel();
		jLabel30.setBounds(10, 40, 90, 20);
		kartuPanel.add(jLabel30);

		jLabel30.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel30.setForeground(Color.WHITE);
		jLabel30.setText("Trace No");
		noTraceTextField = new javax.swing.JTextField();
		noTraceTextField.setBounds(117, 40, 200, 20);
		noTraceTextField.setEditable(false);
		kartuPanel.add(noTraceTextField);

		dpKartuTextField = new JTextField();
		dpKartuTextField.setBounds(117, 70, 200, 20);
		dpKartuTextField.setEditable(false);
		
		dpKartuTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		kartuPanel.add(dpKartuTextField);

		JLabel lblDpKartu = new JLabel();
		lblDpKartu.setBounds(10, 70, 90, 20);
		kartuPanel.add(lblDpKartu);
		lblDpKartu.setText("Dp Kartu");
		lblDpKartu.setForeground(Color.WHITE);
		lblDpKartu.setFont(new Font("Tahoma", Font.BOLD, 12));

		instansiLabel = new JPanel();
		instansiLabel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
		instansiLabel.setBounds(10, 350, 327, 70);
		instansiLabel.setOpaque(false);
		jPanel6.add(instansiLabel);
		instansiLabel.setLayout(null);

		JLabel lblNoLegalisasi = new JLabel();
		lblNoLegalisasi.setBounds(10, 10, 90, 20);
		instansiLabel.add(lblNoLegalisasi);
		lblNoLegalisasi.setText("No. Legalisasi");
		lblNoLegalisasi.setForeground(Color.WHITE);
		lblNoLegalisasi.setFont(new Font("Tahoma", Font.BOLD, 12));
		noLegalisasiTextField = new javax.swing.JTextField();
		noLegalisasiTextField.setBounds(117, 10, 200, 20);
		noLegalisasiTextField.setEditable(false);
		instansiLabel.add(noLegalisasiTextField);
		dpInstansiTextField = new javax.swing.JTextField();
		dpInstansiTextField.setBounds(117, 40, 200, 20);
		dpInstansiTextField.setEditable(false);
		
		dpInstansiTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		instansiLabel.add(dpInstansiTextField);
		jLabel22 = new javax.swing.JLabel();
		jLabel22.setBounds(10, 40, 90, 20);
		instansiLabel.add(jLabel22);

		jLabel22.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
		jLabel22.setForeground(Color.WHITE);
		jLabel22.setText("DP Instansi");
		jLabel22.setPreferredSize(new java.awt.Dimension(75, 15));

		transferPanel = new JPanel();
		transferPanel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
		transferPanel.setBounds(10, 430, 327, 40);
		transferPanel.setOpaque(false);
		jPanel6.add(transferPanel);
		transferPanel.setLayout(null);

		JLabel transferLbl = new JLabel();
		transferLbl.setBounds(10, 10, 90, 20);
		transferPanel.add(transferLbl);
		transferLbl.setText("Transfer");
		transferLbl.setPreferredSize(new Dimension(75, 15));
		transferLbl.setForeground(Color.WHITE);
		transferLbl.setFont(new Font("Tahoma", Font.BOLD, 12));
		dpTransferTextField = new javax.swing.JTextField();
		dpTransferTextField.setBounds(117, 10, 200, 20);
		dpTransferTextField.setEditable(false);
		
		dpTransferTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void insertUpdate(DocumentEvent e) {
				count();
			}
			
			@Override
			public void changedUpdate(DocumentEvent e) {
				count();
			}
		});
		
		transferPanel.add(dpTransferTextField);
		jPanel7.setLayout(null);
		jPanel7.setBounds(580, 10, 370, 585);
		jPanel7.add(jPanel6);
		jPanel7.add(jPanel8);
		jPanel8.setLayout(null);
		jPanel8.add(resetButton);
		jPanel8.add(tundaButton);
		jPanel8.add(bayarButton);
		
		JButton newButton = new JButton();
		newButton.setText("Baru");
		newButton.setBounds(10, 10, 75, 25);
		jPanel8.add(newButton);
		jPanel1.setLayout(null);
		jPanel1.setBounds(10, 10, 560, 585);
		jPanel1.add(jPanel2);
		jPanel1.add(jPanel5);
		jPanel1.add(jPanel4);
		jPanel1.add(jPanel3);

		getContentPane().add(panel1, null);
		panel1.setLayout(null);
		panel1.setSize(950,605);
		panel1.add(jPanel1);
		panel1.add(jPanel7);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	protected void createNewTransaction() {
		SystemID.load();
		jLabel25.setText(""+SystemID.generate("TRX", "S"));
		SystemID.save();
	}

	protected void count() {
		int lens = 0;
		int frame = 0;
		int diskon = 0;
		int total = 0;
		
		int dpCash = 0;
		int dpKartu = 0;
		int dpInstansi = 0;
		int dpTransfer = 0;
		int sisa = 0;
		
		System.out.println();
		
		if (!"".equals(lensPriceTextField.getText())) lens = Integer.parseInt(lensPriceTextField.getText());
		else lens = 0;
		if (!"".equals(framePriceTextField.getText())) frame = Integer.parseInt(framePriceTextField.getText());
		else frame = 0;
		if (!"".equals(diskonTextField.getText())) diskon = Integer.parseInt(diskonTextField.getText());
		else diskon = 0;
		
		if (!"".equals(dpCashTextField.getText())) dpCash = Integer.parseInt(dpCashTextField.getText());
		else dpCash = 0;
		if (!"".equals(dpKartuTextField.getText())) dpKartu = Integer.parseInt(dpKartuTextField.getText());
		else dpKartu = 0;
		if (!"".equals(dpInstansiTextField.getText())) dpInstansi = Integer.parseInt(dpInstansiTextField.getText());
		else dpInstansi = 0;
		if (!"".equals(dpTransferTextField.getText())) dpTransfer = Integer.parseInt(dpTransferTextField.getText());
		else dpTransfer = 0;
		
		total = (lens+frame)-diskon;
		sisa = total - (dpCash+dpKartu+dpInstansi+dpTransfer);
		
		totalBayarTextField.setText(""+total);
		sisaTextField.setText(""+sisa);
	}

	private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {
		
	}

	private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_phoneTxtActionPerformed

	private void mobileTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTxtActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_mobileTxtActionPerformed

	private void lensTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lensTxtActionPerformed

	}//GEN-LAST:event_lensTxtActionPerformed

	private void colorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTxtActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_colorTxtActionPerformed

	private void pdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdTxtActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_pdTxtActionPerformed

	private void frameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameTxtActionPerformed

	}//GEN-LAST:event_frameTxtActionPerformed

	private void lensTxtMousePressed(java.awt.event.MouseEvent evt) {
		frameTransactionController.show(this, new LensDialog(this));
	}

	private void frameTxtMousePressed(java.awt.event.MouseEvent evt) {
		frameTransactionController.show(this, new FrameDialog(this));
	}
	
	private void nameTxtMouseClicked(java.awt.event.MouseEvent evt) {                                     
        frameTransactionController.show(this, new CustomerDialog(this));
    }
	
	private javax.swing.JTextField diskonTextField;
	private javax.swing.JTextField sisaTextField;
	private com.toedter.calendar.JDateChooser bodTxt;
	private javax.swing.JTextField colorTxt;
	private javax.swing.JTextArea descTxt;
	private javax.swing.JTextField totalBayarTextField;
	private javax.swing.JButton exitBtn;
	private javax.swing.JTextField framePriceTextField;
	private javax.swing.JTextField frameTxt;
	private javax.swing.JTextField dpTransferTextField;
	private javax.swing.JButton resetButton;
	private javax.swing.JButton tundaButton;
	private javax.swing.JButton bayarButton;
	private javax.swing.JCheckBox cashChkbox;
	private javax.swing.JCheckBox transferChkbox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel dateLabel;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField noTraceTextField;
	private javax.swing.JTextField noLegalisasiTextField;
	private javax.swing.JTextField dpInstansiTextField;
	private javax.swing.JTextField lensPriceTextField;
	private javax.swing.JTextField lensTxt;
	private javax.swing.JTextField mobileTxt;
	private javax.swing.JTextField nameTxt;
	private indooptik.utility.Panel panel1;
	private javax.swing.JTextField pdTxt;
	private javax.swing.JTextField phoneTxt;
	private JTextField dpCashTextField;
	private JTextField noKartuTextField;
	private JTextField textField_2;
	private JTextField textField_3;
	private JTextField dpKartuTextField;
	private JPanel kartuPanel;
	private JPanel instansiLabel;
	private JPanel transferPanel;
	// End of variables declaration//GEN-END:variables

	@Override
	public void insertUpdate(DocumentEvent e) {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	@Override
	public void removeUpdate(DocumentEvent e) {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	@Override
	public void changedUpdate(DocumentEvent e) {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * @param frameTransactionController the frameTransactionController to set
	 */
	public void setFrameTransactionController(FrameTransactionController frameTransactionController) {
		this.frameTransactionController = frameTransactionController;
	}

	/**
	 * @return the additionTxt
	 */
	/*public javax.swing.JTextField getAdditionTxt() {
        return additionTxt;
    }*/

	/**
	 * @return the amountTxt
	 */
	public javax.swing.JTextField getAmountTxt() {
		return diskonTextField;
	}

	/**
	 * @return the balanceTxt
	 */
	public javax.swing.JTextField getBalanceTxt() {
		return sisaTextField;
	}

	/**
	 * @return the bodTxt
	 */
	public com.toedter.calendar.JDateChooser getBodTxt() {
		return bodTxt;
	}

	/**
	 * @return the colorTxt
	 */
	public javax.swing.JTextField getColorTxt() {
		return colorTxt;
	}

	/**
	 * @return the dpTxt
	 */
	public javax.swing.JTextField getDpTxt() {
		return totalBayarTextField;
	}

	/**
	 * @return the framePriceTxt
	 */
	public javax.swing.JTextField getFramePriceTxt() {
		return framePriceTextField;
	}

	/**
	 * @return the frameTxt
	 */
	public javax.swing.JTextField getFrameTxt() {
		return frameTxt;
	}

	/**
	 * @return the instituteTxt
	 */
	public javax.swing.JTextField getInstituteTxt() {
		return dpTransferTextField;
	}

	/**
	 * @return the lensPriceTxt
	 */
	public javax.swing.JTextField getLensPriceTxt() {
		return lensPriceTextField;
	}

	/**
	 * @return the lensTxt
	 */
	public javax.swing.JTextField getLensTxt() {
		return lensTxt;
	}

	/**
	 * @return the mobileTxt
	 */
	public javax.swing.JTextField getMobileTxt() {
		return mobileTxt;
	}

	/**
	 * @return the nameTxt
	 */
	public javax.swing.JTextField getNameTxt() {
		return nameTxt;
	}

	/**
	 * @return the odAxisTxt
	 */
	/*public javax.swing.JTextField getOdAxisTxt() {
        return odAxisTxt;
    }*/

	/**
	 * @return the odCylTxt
	 *//*
    public javax.swing.JTextField getOdCylTxt() {
        return odCylTxt;
    }

	  *//**
	  * @return the odSphTxt
	  *//*
    public javax.swing.JTextField getOdSphTxt() {
        return odSphTxt;
    }*/

	/**
	 * @return the osAxisTxt
	 */
	/*public javax.swing.JTextField getOsAxisTxt() {
        return osAxisTxt;
    }*/

	/**
	 * @return the osCylTxt
	 *//*
    public javax.swing.JTextField getOsCylTxt() {
        return osCylTxt;
    }

	  *//**
	  * @return the osSphTxt
	  *//*
    public javax.swing.JTextField getOsSphTxt() {
        return osSphTxt;
    }*/

	/**
	 * @return the pdTxt
	 */
	public javax.swing.JTextField getPdTxt() {
		return pdTxt;
	}

	/**
	 * @return the phoneTxt
	 */
	public javax.swing.JTextField getPhoneTxt() {
		return phoneTxt;
	}
}
