/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indooptik.internalframe;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import com.toedter.calendar.JDateChooser;

import indooptik.controller.LensController;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JPanel;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Yoeda H
 */
public class OrderInternalFrame extends javax.swing.JInternalFrame implements DocumentListener{    
    
    private LensController lensController;    
    /**
     * Creates new form DisplayTable
     */
    public OrderInternalFrame() {
        initComponents();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitBtn = new javax.swing.JButton();
        panel1 = new indooptik.utility.Panel();
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBounds(10, 11, 928, 624);
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(10, 100, 70, 20);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(10, 70, 70, 20);
        saveBtn = new javax.swing.JButton();
        saveBtn.setBounds(158, 168, 57, 23);
        editBtn = new javax.swing.JButton();
        editBtn.setBounds(229, 168, 51, 23);
        deleteBtn = new javax.swing.JButton();
        deleteBtn.setBounds(290, 168, 63, 23);
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBounds(12, 268, 904, 311);
        lensTabel = new javax.swing.JTable();
        resetBtn = new javax.swing.JButton();
        resetBtn.setBounds(90, 168, 61, 23);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(10, 40, 50, 20);
        searchTxt = new javax.swing.JTextField();
        searchTxt.setBounds(90, 202, 250, 20);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(12, 204, 19, 15);

        exitBtn.setMnemonic('k');

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setTitle("Order");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("O.S. Sph.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("O.D. Sph.");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        lensTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Jenis Bahan", "Tipe Lensa", "Warna Lensa", "Harga Lensa", "Sph", "Cyl", "Add", "Merk", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lensTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lensTabelMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lensTabel);
        if (lensTabel.getColumnModel().getColumnCount() > 0) {
            lensTabel.getColumnModel().getColumn(0).setMinWidth(0);
            lensTabel.getColumnModel().getColumn(0).setMaxWidth(0);
            lensTabel.getColumnModel().getColumn(3).setMinWidth(110);
            lensTabel.getColumnModel().getColumn(3).setMaxWidth(110);
            lensTabel.getColumnModel().getColumn(4).setMinWidth(0);
            lensTabel.getColumnModel().getColumn(4).setMaxWidth(0);
            lensTabel.getColumnModel().getColumn(5).setMinWidth(50);
            lensTabel.getColumnModel().getColumn(5).setMaxWidth(50);
            lensTabel.getColumnModel().getColumn(6).setMinWidth(50);
            lensTabel.getColumnModel().getColumn(6).setMaxWidth(50);
            lensTabel.getColumnModel().getColumn(7).setMinWidth(50);
            lensTabel.getColumnModel().getColumn(7).setMaxWidth(50);
            lensTabel.getColumnModel().getColumn(9).setMinWidth(40);
            lensTabel.getColumnModel().getColumn(9).setMaxWidth(40);
        }

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Warna");

        searchTxt.setToolTipText("Pencarian berdasarkan kolom - kolom yang ada pada tabel lensa. Pencarian Case Sensitive");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cari");

        getContentPane().add(panel1);
        panel1.setLayout(null);
		panel1.setSize(950,605);
        panel1.add(jPanel1);
        jPanel1.setLayout(null);
        jPanel1.add(jScrollPane1);
        jPanel1.add(jLabel6);
        jPanel1.add(jLabel2);
        jPanel1.add(jLabel1);
        jPanel1.add(resetBtn);
        jPanel1.add(saveBtn);
        jPanel1.add(editBtn);
        jPanel1.add(deleteBtn);
        jPanel1.add(searchTxt);
        jPanel1.add(jLabel3);
        
        JLabel lblLensa = new JLabel();
        lblLensa.setText("Lensa");
        lblLensa.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblLensa.setForeground(Color.WHITE);
        lblLensa.setBounds(10, 10, 50, 20);
        jPanel1.add(lblLensa);
        
        lensTextField = new JTextField();
        lensTextField.setEditable(false);
        lensTextField.setEnabled(false);
        lensTextField.setBounds(90, 10, 150, 20);
        jPanel1.add(lensTextField);
        lensTextField.setColumns(10);
        
        colorTextField = new JTextField();
        colorTextField.setEnabled(false);
        colorTextField.setEditable(false);
        colorTextField.setColumns(10);
        colorTextField.setBounds(90, 41, 150, 20);
        jPanel1.add(colorTextField);
        
        textField = new JTextField();
        textField.setEnabled(false);
        textField.setEditable(false);
        textField.setColumns(10);
        textField.setBounds(90, 71, 50, 20);
        jPanel1.add(textField);
        
        textField_1 = new JTextField();
        textField_1.setEnabled(false);
        textField_1.setEditable(false);
        textField_1.setColumns(10);
        textField_1.setBounds(90, 101, 50, 20);
        jPanel1.add(textField_1);
        
        JLabel lblCyl = new JLabel();
        lblCyl.setText("Cyl.");
        lblCyl.setForeground(Color.WHITE);
        lblCyl.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblCyl.setBounds(150, 70, 30, 20);
        jPanel1.add(lblCyl);
        
        JLabel lblCyl_1 = new JLabel();
        lblCyl_1.setText("Cyl.");
        lblCyl_1.setForeground(Color.WHITE);
        lblCyl_1.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblCyl_1.setBounds(150, 100, 30, 20);
        jPanel1.add(lblCyl_1);
        
        textField_2 = new JTextField();
        textField_2.setEnabled(false);
        textField_2.setEditable(false);
        textField_2.setColumns(10);
        textField_2.setBounds(190, 71, 50, 20);
        jPanel1.add(textField_2);
        
        textField_3 = new JTextField();
        textField_3.setEnabled(false);
        textField_3.setEditable(false);
        textField_3.setColumns(10);
        textField_3.setBounds(190, 101, 50, 20);
        jPanel1.add(textField_3);
        
        lblAxis = new JLabel();
        lblAxis.setText("Axis");
        lblAxis.setForeground(Color.WHITE);
        lblAxis.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblAxis.setBounds(250, 70, 30, 20);
        jPanel1.add(lblAxis);
        
        lblAxis_1 = new JLabel();
        lblAxis_1.setText("Axis");
        lblAxis_1.setForeground(Color.WHITE);
        lblAxis_1.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblAxis_1.setBounds(250, 100, 30, 20);
        jPanel1.add(lblAxis_1);
        
        textField_4 = new JTextField();
        textField_4.setEnabled(false);
        textField_4.setEditable(false);
        textField_4.setColumns(10);
        textField_4.setBounds(277, 71, 50, 20);
        jPanel1.add(textField_4);
        
        textField_5 = new JTextField();
        textField_5.setEnabled(false);
        textField_5.setEditable(false);
        textField_5.setColumns(10);
        textField_5.setBounds(277, 101, 50, 20);
        jPanel1.add(textField_5);
        
        lblAddition = new JLabel();
        lblAddition.setText("Addition");
        lblAddition.setForeground(Color.WHITE);
        lblAddition.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblAddition.setBounds(10, 130, 70, 20);
        jPanel1.add(lblAddition);
        
        textField_6 = new JTextField();
        textField_6.setEnabled(false);
        textField_6.setEditable(false);
        textField_6.setColumns(10);
        textField_6.setBounds(90, 130, 50, 20);
        jPanel1.add(textField_6);
        
        lblPd = new JLabel();
        lblPd.setText("PD");
        lblPd.setForeground(Color.WHITE);
        lblPd.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblPd.setBounds(150, 131, 30, 20);
        jPanel1.add(lblPd);
        
        textField_7 = new JTextField();
        textField_7.setEnabled(false);
        textField_7.setEditable(false);
        textField_7.setColumns(10);
        textField_7.setBounds(190, 132, 50, 20);
        jPanel1.add(textField_7);
        
        JPanel panel = new JPanel();
        panel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
        panel.setBounds(409, 10, 259, 140);
        panel.setOpaque(false);
        jPanel1.add(panel);
        panel.setLayout(null);
        
        lblStatus = new JLabel();
        lblStatus.setBounds(10, 11, 70, 20);
        panel.add(lblStatus);
        lblStatus.setText("Status Order");
        lblStatus.setForeground(Color.WHITE);
        lblStatus.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        lblPengorder = new JLabel();
        lblPengorder.setBounds(10, 43, 70, 20);
        panel.add(lblPengorder);
        lblPengorder.setText("Pengorder");
        lblPengorder.setForeground(Color.WHITE);
        lblPengorder.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        lblKodeOrder = new JLabel();
        lblKodeOrder.setBounds(10, 74, 70, 20);
        panel.add(lblKodeOrder);
        lblKodeOrder.setText("Kode Order");
        lblKodeOrder.setForeground(Color.WHITE);
        lblKodeOrder.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        textField_8 = new JTextField();
        textField_8.setBounds(96, 44, 150, 20);
        panel.add(textField_8);
        textField_8.setColumns(10);
        
        textField_9 = new JTextField();
        textField_9.setBounds(96, 75, 150, 20);
        panel.add(textField_9);
        textField_9.setColumns(10);
        
        lblTanggalOrder = new JLabel();
        lblTanggalOrder.setText("Tgl. Order");
        lblTanggalOrder.setForeground(Color.WHITE);
        lblTanggalOrder.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblTanggalOrder.setBounds(10, 109, 70, 20);
        panel.add(lblTanggalOrder);
        
        orderDate = new JDateChooser();
        orderDate.setBounds(96, 110, 86, 20);
        panel.add(orderDate);
        
        
        lblTanggal = new JLabel("Tanggal");
        lblTanggal.setForeground(Color.WHITE);
        lblTanggal.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblTanggal.setBounds(250, 10, 50, 20);
        jPanel1.add(lblTanggal);
        
        textField_10 = new JTextField();
        textField_10.setEnabled(false);
        textField_10.setEditable(false);
        textField_10.setBounds(310, 10, 70, 20);
        jPanel1.add(textField_10);
        textField_10.setColumns(10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        lensController.reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void lensTabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lensTabelMousePressed
        lensController.chooseData();
    }//GEN-LAST:event_lensTabelMousePressed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        lensController.delete();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        lensController.edit();
    }//GEN-LAST:event_editBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        lensController.save();
    }//GEN-LAST:event_saveBtnActionPerformed
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lensTabel;
    private indooptik.utility.Panel panel1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchTxt;
    private JTextField lensTextField;
    private JTextField colorTextField;
    private JTextField textField;
    private JTextField textField_1;
    private JTextField textField_2;
    private JTextField textField_3;
    private JLabel lblAxis;
    private JLabel lblAxis_1;
    private JTextField textField_4;
    private JTextField textField_5;
    private JLabel lblAddition;
    private JTextField textField_6;
    private JLabel lblPd;
    private JTextField textField_7;
    private JLabel lblStatus;
    private JLabel lblPengorder;
    private JTextField textField_8;
    private JLabel lblKodeOrder;
    private JTextField textField_9;
    private JLabel lblTanggalOrder;
    private JLabel lblTanggal;
    private JTextField textField_10;
    private JDateChooser orderDate;
    // End of variables declaration//GEN-END:variables

    
    /**
     * @return the lensTabel
     */
    public javax.swing.JTable getLensTabel() {
        return lensTabel;
    }

    /**
     * @return the lensTypeTxt
     */
    /**
     * @return the searchTxt
     */
    public javax.swing.JTextField getSearchTxt() {
        return searchTxt;
    }

    /**
     * @param lensController the lensController to set
     */
    public void setLensController(LensController lensController) {
        this.lensController = lensController;
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        lensController.search();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        lensController.search();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        lensController.search();
    }
}
