/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indooptik.jdialog;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author msacool
 */
public class PopUpMessageDialog extends javax.swing.JDialog {

    /**
     * Creates new form PopUpMessageDialog
     */
    public PopUpMessageDialog(String title, Image image, String message) {
        if(title != null) setTitle(title);
		else setTitle("no title");
		setBounds(100, 100, 450, 250);
		getContentPane().setLayout(null);
		
		JPanel imagePnl = new JPanel();
		imagePnl.setBounds(10, 10, 150, 150);
		imagePnl.setLayout(null);
		getContentPane().add(imagePnl);
		
		JPanel messagePnl = new JPanel();
		messagePnl.setBounds(170, 10, 254, 150);
		messagePnl.setLayout(null);
		getContentPane().add(messagePnl);
		
		JLabel messageLbl = new JLabel();
		messageLbl.setBounds(10, 11, 234, 128);
		messagePnl.add(messageLbl);
		if (message != null) messageLbl.setText(message);
		else messageLbl.setText("no message");
		
		JButton confirmBtn = new JButton("OK");
		confirmBtn.setBounds(335, 171, 90, 30);
		getContentPane().add(confirmBtn);
		
		confirmBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
